export interface fakeDataI {
  id: number;
  name: string;
  lastName: string;
  dateOfBirth: string;
  age: string;
  gendre: string;
  city: string;
  department: string;
  username: string;
  email: string;
  [key: string]: any;
}

export const fakeData: fakeDataI[] = [
  {
    id: 1,
    name: 'Juan',
    lastName: 'Pérez',
    dateOfBirth: 'Enero 15 1985',
    age: '38',
    gendre: 'M',
    city: 'Bogotá',
    department: 'Cundinamarca',
    username: 'juanperez85',
    email: 'juan.perez@gmail.com',
  },
  {
    id: 2,
    name: 'Carlos',
    lastName: 'López',
    dateOfBirth: 'Marzo 10 1982',
    age: '41',
    gendre: 'M',
    city: 'Cali',
    department: 'Valle del Cauca',
    username: 'carloslopez82',
    email: 'carlos.lopez@gmail.com',
  },
  {
    id: 3,
    name: 'Ana',
    lastName: 'Martínez',
    dateOfBirth: 'Abril 5 1995',
    age: '28',
    gendre: 'F',
    city: 'Barranquilla',
    department: 'Atlántico',
    username: 'anamartinez95',
    email: 'ana.martinez@gmail.com',
  },
  {
    id: 4,
    name: 'Luis',
    lastName: 'Ramírez',
    dateOfBirth: 'Mayo 30 1988',
    age: '35',
    gendre: 'M',
    city: 'Cartagena',
    department: 'Bolívar',
    username: 'luisramirez88',
    email: 'luis.ramirez@gmail.com',
  },
  {
    id: 5,
    name: 'Sofía',
    lastName: 'Hernández',
    dateOfBirth: 'Junio 25 1992',
    age: '31',
    gendre: 'F',
    city: 'Bucaramanga',
    department: 'Santander',
    username: 'sofiahernandez92',
    email: 'sofia.hernandez@gmail.com',
  },
  {
    id: 6,
    name: 'Andrés',
    lastName: 'Torres',
    dateOfBirth: 'Julio 12 1980',
    age: '43',
    gendre: 'M',
    city: 'Pereira',
    department: 'Risaralda',
    username: 'andrestorres80',
    email: 'andres.torres@gmail.com',
  },
  {
    id: 7,
    name: 'Valentina',
    lastName: 'Cruz',
    dateOfBirth: 'Agosto 18 1993',
    age: '30',
    gendre: 'F',
    city: 'Cúcuta',
    department: 'Norte de Santander',
    username: 'valentinacruz93',
    email: 'valentina.cruz@gmail.com',
  },
  {
    id: 8,
    name: 'Diego',
    lastName: 'Jiménez',
    dateOfBirth: 'Septiembre 22 1987',
    age: '36',
    gendre: 'M',
    city: 'Santa Marta',
    department: 'Magdalena',
    username: 'diegojimenez87',
    email: 'diego.jimenez@gmail.com',
  },
  {
    id: 9,
    name: 'Camila',
    lastName: 'Salazar',
    dateOfBirth: 'Octubre 3 1991',
    age: '32',
    gendre: 'F',
    city: 'Manizales',
    department: 'Caldas',
    username: 'camilasalazar91',
    email: 'camila.salazar@gmail.com',
  },
  {
    id: 10,
    name: 'Felipe',
    lastName: 'Mendoza',
    dateOfBirth: 'Noviembre 14 1984',
    age: '39',
    gendre: 'M',
    city: 'Neiva',
    department: 'Huila',
    username: 'felipemendoza84',
    email: 'felipe.mendoza@gmail.com',
  },
  {
    id: 11,
    name: 'Isabella',
    lastName: 'Rojas',
    dateOfBirth: 'Diciembre 29 1996',
    age: '26',
    gendre: 'F',
    city: 'Pasto',
    department: 'Nariño',
    username: 'isabellarojas96',
    email: 'isabella.rojas@gmail.com',
  },
  {
    id: 12,
    name: 'Javier',
    lastName: 'García',
    dateOfBirth: 'Enero 8 1983',
    age: '40',
    gendre: 'M',
    city: 'Tuluá',
    department: 'Valle del Cauca',
    username: 'javiergarcia83',
    email: 'javier.garcia@gmail.com',
  },
  {
    id: 13,
    name: 'Lucía',
    lastName: 'Vargas',
    dateOfBirth: 'Febrero 17 1994',
    age: '29',
    gendre: 'F',
    city: 'Sincelejo',
    department: 'Sucre',
    username: 'luciavargas94',
    email: 'lucia.vargas@gmail.com',
  },
  {
    id: 14,
    name: 'Sebastián',
    lastName: 'Córdoba',
    dateOfBirth: 'Marzo 21 1986',
    age: '37',
    gendre: 'M',
    city: 'Valledupar',
    department: 'Cesar',
    username: 'sebastiancordoba86',
    email: 'sebastian.cordoba@gmail.com',
  },
  {
    id: 15,
    name: 'Natalia',
    lastName: 'Pineda',
    dateOfBirth: 'Abril 30 1992',
    age: '31',
    gendre: 'F',
    city: 'Riohacha',
    department: 'La Guajira',
    username: 'nataliapineda92',
    email: 'natalia.pineda@gmail.com',
  },
  {
    id: 16,
    name: 'Mateo',
    lastName: 'Sierra',
    dateOfBirth: 'Mayo 15 1989',
    age: '34',
    gendre: 'M',
    city: 'Quibdó',
    department: 'Chocó',
    username: 'mateosierra89',
    email: 'mateo.sierra@gmail.com',
  },
  {
    id: 17,
    name: 'Emilia',
    lastName: 'Cáceres',
    dateOfBirth: 'Junio 11 1995',
    age: '28',
    gendre: 'F',
    city: 'Tumaco',
    department: 'Nariño',
    username: 'emiliacaceres95',
    email: 'emilia.caceres@gmail.com',
  },
  {
    id: 18,
    name: 'Nicolás',
    lastName: 'Salas',
    dateOfBirth: 'Julio 4 1981',
    age: '42',
    gendre: 'M',
    city: 'Cali',
    department: 'Valle del Cauca',
    username: 'nicolassalas81',
    email: 'nicolas.salas@gmail.com',
  },
];
